"""Storage layer with two backends behind one tiny API:

- SQLite (default): local dev and tests. WAL, one connection, RLock.
- Postgres (DATABASE_URL set): production, e.g. Supabase behind Vercel.
  The app's sqlite-flavored SQL ('?' placeholders, cur.lastrowid) is
  adapted by PgCursor; every transaction pins search_path to the isolated
  'darwin' schema so nothing else in the database is ever touched.

DATABASE_URL may hold several comma-separated candidate DSNs (transaction
pooler, session pooler, direct host); the first that connects wins. Handy
when the reachable endpoint differs per network (serverless is usually
IPv4-only, Supabase direct hosts are IPv6).
"""

import re
import sqlite3
import threading
from contextlib import contextmanager

from . import config

_lock = threading.RLock()
_conn = None
_is_pg = False

# Tables whose INSERTs need cur.lastrowid (PgCursor adds RETURNING id).
_ID_TABLES = ("users", "agents", "bounties", "withdrawals", "ledger")

SQLITE_SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
    id            INTEGER PRIMARY KEY,
    email         TEXT NOT NULL UNIQUE,
    name          TEXT NOT NULL,
    token_hash    TEXT NOT NULL UNIQUE,
    kimi_api_key  TEXT,                 -- optional BYO key; else platform key
    balance_micro INTEGER NOT NULL DEFAULT 0,
    created_at    REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS agents (
    id             INTEGER PRIMARY KEY,
    user_id        INTEGER NOT NULL REFERENCES users(id),
    name           TEXT NOT NULL,
    goal           TEXT NOT NULL DEFAULT '',
    model          TEXT NOT NULL,
    status         TEXT NOT NULL DEFAULT 'alive',   -- alive | dead
    token_hash     TEXT NOT NULL UNIQUE,
    balance_micro  INTEGER NOT NULL DEFAULT 0,
    pid            INTEGER,
    born_at        REAL NOT NULL,
    last_burn_at   REAL NOT NULL,
    died_at        REAL,
    cause_of_death TEXT
);

CREATE TABLE IF NOT EXISTS ledger (
    id            INTEGER PRIMARY KEY,
    ts            REAL NOT NULL,
    owner_kind    TEXT NOT NULL,        -- 'user' | 'agent' | 'platform'
    owner_id      INTEGER NOT NULL,
    delta_micro   INTEGER NOT NULL,
    balance_after INTEGER NOT NULL,
    kind          TEXT NOT NULL,
    memo          TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS bounties (
    id           INTEGER PRIMARY KEY,
    poster_id    INTEGER NOT NULL REFERENCES users(id),
    title        TEXT NOT NULL,
    spec         TEXT NOT NULL,
    reward_micro INTEGER NOT NULL,
    status       TEXT NOT NULL DEFAULT 'open',
    -- open | claimed | submitted | paid | cancelled
    claimed_by   INTEGER REFERENCES agents(id),
    result       TEXT,
    created_at   REAL NOT NULL,
    updated_at   REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS withdrawals (
    id          INTEGER PRIMARY KEY,
    user_id     INTEGER NOT NULL REFERENCES users(id),
    micro       INTEGER NOT NULL,
    destination TEXT NOT NULL,
    status      TEXT NOT NULL DEFAULT 'pending',  -- pending | paid | cancelled
    created_at  REAL NOT NULL,
    updated_at  REAL NOT NULL
);

-- processed Stripe checkout sessions, for webhook replay idempotency
CREATE TABLE IF NOT EXISTS stripe_events (
    id TEXT PRIMARY KEY,
    ts REAL NOT NULL
);

-- shared coordination state, e.g. the opportunistic reaper's last pass
CREATE TABLE IF NOT EXISTS meta (
    key   TEXT PRIMARY KEY,
    value REAL NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_ledger_owner ON ledger(owner_kind, owner_id);
CREATE INDEX IF NOT EXISTS idx_bounties_status ON bounties(status);
CREATE INDEX IF NOT EXISTS idx_withdrawals_status ON withdrawals(status);
"""

PG_SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         TEXT NOT NULL UNIQUE,
    name          TEXT NOT NULL,
    token_hash    TEXT NOT NULL UNIQUE,
    kimi_api_key  TEXT,
    balance_micro BIGINT NOT NULL DEFAULT 0,
    created_at    DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS agents (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT NOT NULL REFERENCES users(id),
    name           TEXT NOT NULL,
    goal           TEXT NOT NULL DEFAULT '',
    model          TEXT NOT NULL,
    status         TEXT NOT NULL DEFAULT 'alive',
    token_hash     TEXT NOT NULL UNIQUE,
    balance_micro  BIGINT NOT NULL DEFAULT 0,
    pid            BIGINT,
    born_at        DOUBLE PRECISION NOT NULL,
    last_burn_at   DOUBLE PRECISION NOT NULL,
    died_at        DOUBLE PRECISION,
    cause_of_death TEXT
);

CREATE TABLE IF NOT EXISTS ledger (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts            DOUBLE PRECISION NOT NULL,
    owner_kind    TEXT NOT NULL,
    owner_id      BIGINT NOT NULL,
    delta_micro   BIGINT NOT NULL,
    balance_after BIGINT NOT NULL,
    kind          TEXT NOT NULL,
    memo          TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS bounties (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poster_id    BIGINT NOT NULL REFERENCES users(id),
    title        TEXT NOT NULL,
    spec         TEXT NOT NULL,
    reward_micro BIGINT NOT NULL,
    status       TEXT NOT NULL DEFAULT 'open',
    claimed_by   BIGINT REFERENCES agents(id),
    result       TEXT,
    created_at   DOUBLE PRECISION NOT NULL,
    updated_at   DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS withdrawals (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users(id),
    micro       BIGINT NOT NULL,
    destination TEXT NOT NULL,
    status      TEXT NOT NULL DEFAULT 'pending',
    created_at  DOUBLE PRECISION NOT NULL,
    updated_at  DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS stripe_events (
    id TEXT PRIMARY KEY,
    ts DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS meta (
    key   TEXT PRIMARY KEY,
    value DOUBLE PRECISION NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_ledger_owner ON ledger(owner_kind, owner_id);
CREATE INDEX IF NOT EXISTS idx_bounties_status ON bounties(status);
CREATE INDEX IF NOT EXISTS idx_withdrawals_status ON withdrawals(status);
"""

_INSERT_RE = re.compile(
    r"^\s*INSERT\s+INTO\s+(" + "|".join(_ID_TABLES) + r")\b", re.IGNORECASE
)


class PgCursor:
    """Adapts a psycopg cursor to the sqlite-flavored calls the app makes:
    '?' placeholders and .lastrowid after INSERT."""

    def __init__(self, cur):
        self._cur = cur
        self.lastrowid = None

    def execute(self, sql, params=()):
        sql = sql.replace("?", "%s")
        if _INSERT_RE.match(sql) and "RETURNING" not in sql.upper():
            self._cur.execute(sql + " RETURNING id", params)
            row = self._cur.fetchone()
            self.lastrowid = row["id"] if row else None
        else:
            self._cur.execute(sql, params)
        return self

    def fetchone(self):
        return self._cur.fetchone()

    def fetchall(self):
        return self._cur.fetchall()

    @property
    def rowcount(self):
        return self._cur.rowcount

    def close(self):
        self._cur.close()


def _connect_pg():
    import psycopg
    from psycopg.rows import dict_row

    last_err = None
    for dsn in config.DATABASE_URLS:
        try:
            conn = psycopg.connect(
                dsn,
                row_factory=dict_row,
                autocommit=True,  # we issue explicit BEGIN/COMMIT ourselves
                prepare_threshold=None,  # required behind transaction poolers
                connect_timeout=10,
            )
            with conn.cursor() as c:
                c.execute("BEGIN")
                c.execute(f"SET LOCAL search_path TO {config.PG_SCHEMA_NAME}")
                c.execute(PG_SCHEMA)
                c.execute("COMMIT")
            return conn
        except Exception as e:  # try the next candidate DSN
            last_err = e
    raise last_err


def connect(path: str | None = None):
    global _conn, _is_pg
    with _lock:
        if _conn is None:
            if config.DATABASE_URLS:
                _conn = _connect_pg()
                _is_pg = True
            else:
                _conn = sqlite3.connect(
                    path or config.DB_PATH, check_same_thread=False
                )
                _conn.row_factory = sqlite3.Row
                _conn.execute("PRAGMA journal_mode=WAL")
                _conn.execute("PRAGMA foreign_keys=ON")
                _conn.executescript(SQLITE_SCHEMA)
                _is_pg = False
        return _conn


def _reset_conn():
    global _conn
    with _lock:
        if _conn is not None:
            try:
                _conn.close()
            except Exception:
                pass
        _conn = None


def reset_for_tests(path: str) -> None:
    _reset_conn()
    connect(path)


def _begin(write: bool):
    """Open a transaction, reconnecting once if a pooled/idle Postgres
    connection has gone away underneath us."""
    for attempt in (0, 1):
        conn = connect()
        try:
            if _is_pg:
                cur = PgCursor(conn.cursor())
                cur.execute("BEGIN")
                cur.execute(f"SET LOCAL search_path TO {config.PG_SCHEMA_NAME}")
            else:
                cur = conn.cursor()
                cur.execute("BEGIN IMMEDIATE" if write else "BEGIN")
            return conn, cur
        except Exception:
            if attempt == 1 or not _is_pg:
                raise
            _reset_conn()


def _finish(conn, commit: bool) -> None:
    if _is_pg:
        conn.execute("COMMIT" if commit else "ROLLBACK")
    else:
        conn.commit() if commit else conn.rollback()


@contextmanager
def tx():
    with _lock:
        conn, cur = _begin(write=True)
        try:
            yield cur
            _finish(conn, commit=True)
        except BaseException:
            _finish(conn, commit=False)
            raise
        finally:
            cur.close()


@contextmanager
def read():
    with _lock:
        conn, cur = _begin(write=False)
        try:
            yield cur
        finally:
            _finish(conn, commit=False)
            cur.close()
